### ISSUE TITLE
Setup staging environment for metanorma.org

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/gsod#10]
From @strogonoff :
> The documentation team wants to have a sandbox or staging for Metanorma.com, I believe that might require an infrastructure setup action?
> They want to play around with Liquid/Jekyll

**Comment by ronaldtse** [comment]
We already setup a staging environment for metanorma.org, all you have to do is to push content to the `staging` branch there.

**Comment by ronaldtse** [comment]
Whoops, there is an authentication page. Let me take authentication down.

**Comment by kickoke** [comment]
Thank you very much!

**Comment by ronaldtse** [comment]
@kickoke @techtrailhead the staging site is publicly accessible now:
https://staging-www.metanorma.com

If you push content to the https://github.com/metanorma/metanorma.org repository's `staging` branch, you will see the content deployed at the site.

**Comment by ronaldtse** [comment]
(Thanks @phuonghuynh for fixing this)
