### ISSUE TITLE
Schedule Metanorma user interview for GSoD

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/gsod#2]
As per discussion today we will schedule a Metanorma user interview for the writers to better understand the needs of Metanorma users/authors.

@ronaldtse will find out and arrange...

**Comment by kickoke** [comment]
Any news on this issue? :)

**Comment by ronaldtse** [comment]
I have reached out, will update!

**Comment by ronaldtse** [comment]
Awaiting confirmation of date/time for meeting.

**Comment by ronaldtse** [comment]
Interview completed with Scott Simmons of OGC. Will schedule with other OGC staff.

**Comment by kickoke** [comment]
@ronaldtse I think the meeting with Scott was very insightful. 
I'm not sure if we need another meeting at the moment. 
Is there still a need for discussing topics that I'm not aware of? 
Or should we ask the same questions and see if there is a different perspective?

**Comment by ronaldtse** [comment]
@kickoke I will organise two other meetings:
1. OGC operational perspective that is not covered by Scott. Scott is mostly strategic.
2. IETF user perspective with Marc.

**Comment by ronaldtse** [comment]
Contacted will update with info.

**Comment by kickoke** [comment]
Thank you!

**Comment by kickoke** [comment]
We've conducted user interviews that helped @techtrailhead improve the flavor documentation.
