### ISSUE TITLE
Develop schedule/timeline for deliverables

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/gsod#3]
For Metanorma
* Audit report of the current state of documentation
* Information architecture
* Metanorma authoring guide for new users
* SDO-specific “pilot” authoring guides for IETF, OGC, ISO and another flavor

For GSoD
* GSoD project case study

**Comment by ronaldtse** [comment]
I've added a placeholder in the README, please feel free to fill in!

**Comment by kickoke** [comment]
I've added the timeline to the README. If we'll need to adjust throughout the project, I'll let you know.
